import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ShoppingCartProvider } from "./context/ShoppingCartContext";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ShoppingCartProvider>
          <Navbar />
          <Toaster
            richColors
            position="top-center"
            // toastOptions={{
            //   style: {
            //     background: "#28CEE7",
            //   },
            // }}
          />
          {children}
          <Footer />
        </ShoppingCartProvider>
      </body>
    </html>
  );
}
